#initial build:
#  docker-compose -f docker-compose-elastic-mongo.yml create 
#
#run:
#  docker-compose -f docker-compose-elastic-mongo.yml start db
#  docker-compose -f docker-compose-elastic-mongo.yml start search
#  docker-compose -f docker-compose-elastic-mongo.yml up
version: '2'
services:
  db:
    image: mongo
    expose: 
     - "27017"
  search:
    image: elasticsearch
    expose:
     - "9200"
  api:
    build: .
    environment:
      - PORT=3003
    #volumes:
    #  - .:/usr/src/app
    ports:
      - "3003:3003"
    depends_on:
      - db
      - search
